version: "3"

services:
  db:
    container_name: meli_frescos_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3333:3306
    command: mysqld --default-authentication-plugin=mysql_native_password